### PR TITLE
Torben algorithm with STL-like interface

### PR DESCRIPTION
**Pull request by KeitaRckPn**
This is a new version of median calculation program which uses a Torben function with STL-like interface. I also add a test program (test_median_calculation.cpp), but we have to think about a way to share fits files to run the test. Currently, the test program is designed to use the 10 fits files we've been  using, but each file is 10 ~ 20MB. So, I feel that is too large to upload to this repository. What do you think?

### CODE REVIEW

**Comment by mcfadden8** [comment]
Thanks @KeitaRckPn, do you know whether those 10 files have already been compressed with [fpack](https://heasarc.gsfc.nasa.gov/fitsio/fpack/)?

**Comment by mcfadden8** [comment]
@KeitaRckPn, please resolve the conflicts that are appearing and push those changes to here as well.

Thanks,

**Comment by KeitaRckPn** [comment]
@mcfadden8 I only checked uncompressed version. Each compressed file (~.fz) is 3.5MB. I also resolved conflicts.

**Comment by mcfadden8** [comment]
Thanks @KeitaRckPn, if you can make the test work with just 4 files, then I would say we should go ahead and check 4 of these compressed data files in.  Will the test work with 4 instead of 10?

Thanks,

**Comment by KeitaRckPn** [comment]
@mcfadden8 Yes, the test program works with 4 files if I change the correct median values written in the program. I'll update the program and commit the 4 files.

**Comment by KeitaRckPn** [comment]
I uploaded 4 compressed fits files for test.

**Comment by mcfadden8** [comment]
@KeitaRckPn, thank you very much for the modifications!

If you could modify one more file, I would appreciate it.  Please add a command to the regression test script located [here](https://github.com/LLNL/umap/blob/develop/tests/regression_tests/run_regression_tests.sh) that we can run.

Thanks!

**Comment by KeitaRckPn** [comment]
@mcfadden8 hi Marty, I have two questions:
1. path to the test data under test/median_calculation/data/
Can I just use relative path to access the data from the script?

2. run funpack
Do you know how to call funpack from the script?

**Comment by mcfadden8** [comment]
Relative pathnames should be fine.

What do you need funpack for?

**Comment by KeitaRckPn** [comment]
Oh, can we directly read compressed fits files with cfits? I was thinking to use funpack for unpacking the files.

**Comment by mcfadden8** [comment]
Good point.  Hmm.  Lets just go ahead and submit the uncompressed files then.  They are 10mb each right?

**Comment by mcfadden8** [comment]
That works.  Just tar/compress then.  Thanks

**Comment by KeitaRckPn** [comment]
@mcfadden8 Marty, I added a test case to the regression test script. Could you check that?

**Comment by mcfadden8** [comment]
Looks good @KeitaRckPn, do you have any more changes you want to make?  If not, I will approve and merge.

**Comment by mcfadden8** [comment]
@KeitaRckPn, and I assume you have run this script?  If so, I will consider the regression tests to have passed.

**Comment by KeitaRckPn** [comment]
@mcfadden8 That's all I have now. Yes, I run the script by myself. So, it should pass regression test.

**Pull request merged**
