### PR TITLE
Add utility functions from ULC project; add median calculation program for mmap

### PR DESCRIPTION
**Pull request by KeitaRckPn**

### CODE REVIEW

**Comment by mayagokhale** [comment]
I agree. I would like to avoid boost dependence.

**Comment by KeitaRckPn** [comment]
1. Why introduce Boost dependency?
Boost is for reading compressed  files in BFS program, which I haven't committed yet. I can remove the features from the BFS program. Also, the median calculation program doesn't have dependencies with boost.

2. We need to make sure this is using cmake and should be set to install HPP files for projects into install target.
Actually, I have a question about this. Is there any way to compile my program without UMAP features? Since one of the motivations to implement the median calculation program with MMAP is that it does't have dependency with UMAP and the new kernel features, I first committed the version without using cmake so that we can discuss this matter.

**Comment by mayagokhale** [comment]
cmake is not related to UMap. We're following the practice of using cmake in this particular git project.

**Comment by mcfadden8** [comment]
Our test programs decide whether to use mmap() versus umap() at runtime via a “—usemmap” command-line switch.  Take a look at the tests/umapsort project.  It uses a library that collects command-line arguments.  You can either modify your test program to use these command-line arguments or craft your own.

Marty

**Comment by KeitaRckPn** [comment]
I changed to use cmake for my program and removed boost dependency. I also committed the new version to share current status.

>Our test programs decide whether to use mmap() versus umap() at runtime via a “—usemmap” command-line switch.  Take a look at the tests/umapsort project.  It uses a library that collects command-line arguments.  You can either modify your test program to use these command-line arguments or craft your own.
Okay, I'll check that.

**Comment by KeitaRckPn** [comment]
I've created a program which selects mmap or umap at run-time.
I have a question about taking command line options that are only required by the median calculation test, e.g., frame size. I'm wondering what is a good way/design to do that in this project.

**Comment by mcfadden8** [comment]
Good question.

It might be a good idea to have the program pre-process the command line arguments and process arguments local to the program before passing the remaining arguments to the library function to process the generic arguments.

Marty

**Comment by mayagokhale** [comment]
That's a good idea. We do have to prominently document the umap library command line options to avoid collision between the user application option names and umap.

**Comment by KeitaRckPn** [comment]
Okay, that's good idea. I'll change my program.

**Comment by KeitaRckPn** [comment]
Because I couldn't find out a good way to parse command line options in a user program first and give the rest of them to the library, I gave up implement the feature today... I'll do that after I come back from Japan. Could you perform tests directly editing some variables in tests/FITS/median_calculation.cpp? 

There are only 3 values you need to change. Specifically, the following varibales:
 cube.size_x = 1024; // width of the frame
 cube.size_y = 1024; // heigh of the frame
 cube.size_k = 10; // number of frames
You can find the variables at the bigining of the main function.

Here is an example to run the program:
./tests/FITS/median_calculation  --usemmap --noinit -n 10 -f /l/ssd/cube
-n: number of input files (must be equal to the number of frames, or variable size_k, if you map multiple files)
-f: prefix of input files. An actual file name is going to be /l/ssd/cube_N, where N is a file number. if you use only single file, the given file name is directly used.

Please let me know if you have any questions.

**Comment by mcfadden8** [comment]
When I attempt to run this with 100 files on a node configured with 134GB of free memory, I get an 'mprotect cannot allocate memory' error.

**Comment by KeitaRckPn** [comment]
Okay... I'm trying to fix the problem. I'll let you know when I find
something.
Keita

2018-01-03 3:41 GMT+09:00 Marty McFadden <notifications@github.com>:

**Comment by mcfadden8** [comment]
Yesterday, I refactored code and fixed the problem.  Let’s discuss when you are available.

**Comment by KeitaRckPn** [comment]
I modified my program to use the new umt_closeandunmap_mf(). For now, it works with the way I shared before, that is, you need to change some hard-coded values. I'm working on the problem now. Once I fixed the problem, I'll close this pull request and create a new one.

**Pull request closed without merging**
