### PR TITLE
Minor README updates

### PR DESCRIPTION
**Pull request by IanLee1521**

### CODE REVIEW

**Comment by IanLee1521** [comment]
Not a problem! I see it as one of the things I can do to help new projects.

Actually, I'm about to make one other change, stand by for #2 !

**Comment by IanLee1521** [comment]
@mcfadden8 -- helpful tip, after you merge the pull request, it is probably a good idea to delete the branch. You should see a button just above this comment in the thread to do just that (I think it might also be an option when you do the merge)

**Comment by mcfadden8** [comment]
Thanks Ian,


I was under the impression that I (the merger) should allow for the person who generated the PR to delete their branch?  Otherwise, I might be deleting a branch that they are still working on?


Marty


________________________________

**Comment by IanLee1521** [comment]
Nod.

So this ability should (will?) only show up when the branch is actually *in* this repository, which I was able to do since I'm an org admin.

In the normal case, you're correct, and GitHub will do this for you. If I was an external contributor with no privileges in this repo, I would fork it and make my branch there, and it would be on me to clean that up. You actually wouldn't be able to (I don't think).

But in the first case, where it's actually a branch in this repository, you'll almost always want to clean them up. There is also a "Restore Branch" button now that one could use to restore it if deleted on accident. And, if I really needed, I could push it again from my local clone.

Hope that clarifies?

**Pull request merged**
