### PR TITLE
Add --usemmap support for FITS.

### PR DESCRIPTION
**Pull request by mcfadden8**
Functional
testlib
  Refactored umt_openandmap_mf() and umt_closeandunmap_mf()
  implementations to C++.  Also, removed duplication of
  implementation in umt_openandmap()/umt_openandmap_mf()
  and umt_closeandunmap()/umt_closeandunmap_mf()
  respectively.

  Added --usemmap cabability to umt_openandmap_mf() and
  umt_closeandunmap_mf() allowing for FITS files configured
  as data-only files to be contiguously mapped to a single
  large virtual region of memory.

  Removed implementation of umt_openandmap_fits2() and
  umt_closeandunmap_fits2() respectively since private
  files are no longer needed now that there is a threaded
  version of the umap() library.

  Changed the test library to always use the multi-file
  data-structures.  In the case of a single file, the
  multi-file structure is still used with num_files set
  to "1".  This enabled us to remove a significant
  amount of code duplication.

Cleanup
 FITS
  Added program (exdata_fits) to FITS test project that will
  create separate data files from the for each fits file.

  Stopped compiling the 'multiple-private' FITS test programs
  now that umap() is threaded.

  Changed num_backing_file to num_backing_files in
  umap_backing_file structure.

  Code cleanup to eliminate compilation warnings.

 testlib
  Renamed "fnum" to "num_files" in test library options
  structure.

  Renamed "fn" to "filename" in test library options
  structure.

  Renamed umt_closeandunmap_fits() to umt_closeandunmap_mf()

  Renamed umt_openandmap_fits() to umt_openandmap_mf()

### CODE REVIEW

**Comment by KeitaRckPn** [comment]
Hi Marty,

I'm wondering what is a good way to merge this update to my code without messing up commit logs. Here is what I'm thinking.

1) I test this code creating a new branch in my repository (I'll discard this branch after finishing the test)
2) you merge this pull request to LLNL/umap/develop
3) I marge LLNL/umap/develop to my develop branch
4) I change my program and commit to pull request#19

What do you think?

**Comment by mcfadden8** [comment]
So I should go ahead and merge this PR (feature/fits_with_mmap) to develop?  Once I get done, you will create a new branch from develop that contains the changes in this PR and then generate a new PR with your updates?

**Comment by KeitaRckPn** [comment]
Okay, how about this?
After you merging this PR, I'll merge it to my develop branch and modify my program within the branch (I won't create a new branch). Then, I'll generate a new PR with the updates (so, I'll discardPR#19 and make PR#21).

**Comment by mcfadden8** [comment]
That works.  I'll merge this now.

**Pull request merged**
