### PR TITLE
General Cleanup

### PR DESCRIPTION
**Pull request by egreen77**
Cleanup
* Cleaned up usage of std namespace
* Fixed C-compatibility in umap.h
* Disabled some debug messages from being generated when logging is disabled

Build system
* Removed spindle logger from build when logging is disabled
* Added pthreads to umap library dependencies

### CODE REVIEW

**Comment by mcfadden8** [comment]
Thanks @egreen77, why the removal of using statements from implementation files?  Which specific problem was being fixed?

**Comment by mcfadden8** [comment]
Thanks for the C-compatibility fixes in umap.h, those look good.

**Comment by egreen77** [comment]
> Thanks @egreen77, why the removal of using statements from implementation files? Which specific problem was being fixed?

This is more of a best-practices sort of change. Generally, it's better to control what you have in your namespaces, especially for production libraries.

See also: https://google.github.io/styleguide/cppguide.html#Namespaces

**Comment by mcfadden8** [comment]
Thanks.  This is fine, I was just trying to figure out whether something specifically was broken.

I would also like to get the entire umpire library under an "Umpire" namespace (with the only exception being the few C interface files).  If you're interested, it would be great if you could take a look at that.

**Pull request merged**
